apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: auraquant-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 2   # Always run at least 2 pods
  maxReplicas: 10  # Scale up to a maximum of 10 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # Target 80% CPU utilization. If pods go above this, a new one is created.
          averageUtilization: 80